name: setup-vsdevenv

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest' ]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: ./
        with:
          winsdk: 10.0.22621.0
      - run: 'cl /EHsc /Fe:test.exe tests\\test.cpp && .\\test.exe'
        shell: cmd
        if: runner.os == 'Windows'

